sonar.projectKey=optic2
sonar.projectName=optic2
sonar.projectVersion=1.0

sonar.sources=frontend/src,backend/app
sonar.tests=frontend/src/tests,backend/tests

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/htmlcov/**,**/.pytest_cache/**,**/__pycache__/**,**/playwright-report/**,**/test-results/**,frontend/src/tests/**,backend/tests/**,**/seed_*.py,**/ver_*.py,**/crear_*.py,**/migrar_*.py,**/diagnostico_*.py

sonar.test.inclusions=frontend/src/tests/**/*.test.js,frontend/src/tests/**/*.test.jsx,backend/tests/**/*.py
sonar.test.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/htmlcov/**,**/.pytest_cache/**,**/__pycache__/**,**/playwright-report/**,**/test-results/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.sourceEncoding=UTF-8