from app.core.database import Base

from app.models.user import User, UserRole
from app.models.student import (
    Student,
    StudentAcademicHistory,
    StudentAcademicHistoryStatus,
    StudentCourseEnrollment,
    StudentEnrollmentStatus,
)
from app.models.teacher import Teacher, TeacherAvailability
from app.models.course import Course, CourseSection
from app.models.classroom import Classroom, ClassroomType
from app.models.schedule import (
    AcademicSchedule,
    ScheduleBlock,
    ScheduleStatus,
    ScheduleType,
    StudentSchedule,
    StudentScheduleBlock,
)
from app.models.environmental_metric import EnvironmentalMetric
from app.models.academic import (
    AcademicPeriod,
    AcademicPeriodStatus,
    AcademicProgram,
    AcademicProgramStatus,
    Campus,
    CoursePrerequisite,
    CurriculumCourse,
    CurriculumCourseType,
    CurriculumPlan,
    CurriculumPlanStatus,
    ElectiveArea,
    ElectiveBankCourse,
    Faculty,
    PrerequisiteType,
)
from app.models.offering import (
    OfferingConflict,
    OfferingConflictSeverity,
    OfferingConflictType,
    OfferingModality,
    OfferingShift,
    OfferingStatus,
    SectionOffering,
    SectionRequirement,
)
from app.models.schedule_change_request import (
    ScheduleChangeRequest,
    ScheduleChangeRequestStatus,
    ScheduleChangeRequestType,
)
from app.models.traceability import (
    AuditAction,
    AuditLog,
    Notification,
    NotificationType,
    RelatedEntityType,
    ScheduleChangeHistory,
    ScheduleChangeType,
    SchedulePublicationHistory,
)

__all__ = [
    "Base",
    "User",
    "UserRole",
    "Student",
    "StudentCourseEnrollment",
    "StudentAcademicHistory",
    "StudentAcademicHistoryStatus",
    "StudentEnrollmentStatus",
    "Teacher",
    "TeacherAvailability",
    "Course",
    "CourseSection",
    "Classroom",
    "ClassroomType",
    "AcademicSchedule",
    "ScheduleBlock",
    "StudentSchedule",
    "StudentScheduleBlock",
    "EnvironmentalMetric",
    "ScheduleStatus",
    "ScheduleType",
    "AcademicPeriod",
    "AcademicPeriodStatus",
    "AcademicProgram",
    "AcademicProgramStatus",
    "Campus",
    "Faculty",
    "CurriculumPlan",
    "CurriculumPlanStatus",
    "CurriculumCourse",
    "CurriculumCourseType",
    "CoursePrerequisite",
    "PrerequisiteType",
    "ElectiveBankCourse",
    "ElectiveArea",
    "SectionOffering",
    "SectionRequirement",
    "OfferingConflict",
    "OfferingModality",
    "OfferingShift",
    "OfferingStatus",
    "OfferingConflictType",
    "OfferingConflictSeverity",
    "ScheduleChangeRequest",
    "ScheduleChangeRequestStatus",
    "ScheduleChangeRequestType",
    "Notification",
    "NotificationType",
    "RelatedEntityType",
    "AuditLog",
    "AuditAction",
    "SchedulePublicationHistory",
    "ScheduleChangeHistory",
    "ScheduleChangeType",
]
