"""add student schedule blocks

Revision ID: 43a31e08c46e
Revises: bbbb49571423
Create Date: 2026-05-17 21:28:11.172738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a31e08c46e'
down_revision: Union[str, None] = 'bbbb49571423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_schedule_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_schedule_id', sa.Integer(), nullable=False),
    sa.Column('schedule_block_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_block_id'], ['schedule_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_schedule_id'], ['student_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_schedule_blocks_id'), 'student_schedule_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_student_schedule_blocks_schedule_block_id'), 'student_schedule_blocks', ['schedule_block_id'], unique=False)
    op.create_index(op.f('ix_student_schedule_blocks_student_schedule_id'), 'student_schedule_blocks', ['student_schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_schedule_blocks_student_schedule_id'), table_name='student_schedule_blocks')
    op.drop_index(op.f('ix_student_schedule_blocks_schedule_block_id'), table_name='student_schedule_blocks')
    op.drop_index(op.f('ix_student_schedule_blocks_id'), table_name='student_schedule_blocks')
    op.drop_table('student_schedule_blocks')
    # ### end Alembic commands ###
